stages:
  - build
  - test
  - sonarqube-check

build:
  tags:
    - shell
  stage: build
  script:
    - ./gradlew --continue build --stacktrace -x test

test:
  tags:
    - shell
  stage: test
  script:
    - ./gradlew test --continue
  artifacts:
    expire_in: 5 day
    reports:
      junit:
        - model/build/test-results/test/TEST-*.xml
        - controller/build/test-results/test/TEST-*.xml
        - view/build/test-results/test/TEST-*.xml
    paths:
      - controller/build/reports/
      - model/build/reports/
      - view/build/reports/
    when: always

sonarqube-check:
  stage: sonarqube-check
  variables:
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project required by the analysis task
  tags:
    - shell
  script: ./gradlew build jacocoTestReport sonar -Dsonar.token=$SONAR_TOKEN
  allow_failure: true
  only:
    - merge_requests
    - main
    - implementation
